// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zj5q8vz87OXpvDF6c8UZZoc8iP3zIzY',
    appId: '1:595438480456:web:6339549ee18cb0662cfc7d',
    messagingSenderId: '595438480456',
    projectId: 'app-para-la-gestion-de-treas',
    authDomain: 'app-para-la-gestion-de-treas.firebaseapp.com',
    storageBucket: 'app-para-la-gestion-de-treas.firebasestorage.app',
    measurementId: 'G-8BNEM3CRFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGTFT_AoN2CZhYY2sijUeSsTvvltvFTQ',
    appId: '1:595438480456:android:30a8e319b091eb532cfc7d',
    messagingSenderId: '595438480456',
    projectId: 'app-para-la-gestion-de-treas',
    storageBucket: 'app-para-la-gestion-de-treas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMlRHCTOb5YBZPgBKEJT3UK6qZc_SWN4',
    appId: '1:595438480456:ios:af1c8e0af3676be82cfc7d',
    messagingSenderId: '595438480456',
    projectId: 'app-para-la-gestion-de-treas',
    storageBucket: 'app-para-la-gestion-de-treas.firebasestorage.app',
    androidClientId: '595438480456-7r4cmaa82s2hflftdvmq6kjp9k6rl0vp.apps.googleusercontent.com',
    iosClientId: '595438480456-vjuajn989bf82arko4p99ech91nngu19.apps.googleusercontent.com',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMlRHCTOb5YBZPgBKEJT3UK6qZc_SWN4',
    appId: '1:595438480456:ios:af1c8e0af3676be82cfc7d',
    messagingSenderId: '595438480456',
    projectId: 'app-para-la-gestion-de-treas',
    storageBucket: 'app-para-la-gestion-de-treas.firebasestorage.app',
    androidClientId: '595438480456-7r4cmaa82s2hflftdvmq6kjp9k6rl0vp.apps.googleusercontent.com',
    iosClientId: '595438480456-vjuajn989bf82arko4p99ech91nngu19.apps.googleusercontent.com',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2zj5q8vz87OXpvDF6c8UZZoc8iP3zIzY',
    appId: '1:595438480456:web:d6296f3261e4bbd82cfc7d',
    messagingSenderId: '595438480456',
    projectId: 'app-para-la-gestion-de-treas',
    authDomain: 'app-para-la-gestion-de-treas.firebaseapp.com',
    storageBucket: 'app-para-la-gestion-de-treas.firebasestorage.app',
    measurementId: 'G-SF97Y1ZZSL',
  );
}
